- name: Install Pimox
  hosts: proxmox_rpies
  become: true
  tasks:
    - name: Download Pimox install script
      shell: curl -O https://raw.githubusercontent.com/alejandro-du/pimox-ansible-playbooks/main/RPiOS64-IA-Install.sh
      args:
        creates: RPiOS64-IA-Install.sh

    - name: Make the Pimox install script executable
      file:
        path: RPiOS64-IA-Install.sh
        mode: '0755'

    - name: Run the Pimox install script
      shell: |
        ./RPiOS64-IA-Install.sh <<EOF
        {{ hostname }}
        {{ new_ip }}
        y
        {{ bridge_ip }}
        y
        {{ new_root_password }}
        {{ new_root_password }}
        EOF
