- name: Install Pimox
  hosts: rpies
  become: true

  tasks:
    tasks:
      - name: Run commands as root
        become: true
        become_user: root
        shell: |
          sudo -s
          curl https://raw.githubusercontent.com/alejandro-du/pimox-ansible-playbooks/main/RPiOS64-IA-Install.sh > RPiOS64-IA-Install.sh
          chmod +x RPiOS64-IA-Install.sh
          echo "
          {{ hostname }} {{ new_ip }} {{ internal_ip }} y y {{ new_root_password }} {{ new_root_password }}" | ./RPiOS64-IA-Install.sh
