- name: Install Pimox
  hosts: rpies
  become: true

  tasks:
    tasks:
      - name: Run commands as root
        become: true
        become_user: root
        shell: |
          sudo -s
          curl https://raw.githubusercontent.com/pimox/pimox7/master/RPiOS64-IA-Install.sh > RPiOS64-IA-Install.sh
          chmod +x RPiOS64-IA-Install.sh
          echo "
          rpi01.local 192.168.1.151/24 y y Password123! Password123!" | ./RPiOS64-IA-Install.sh
