---
- name: Add periodic WiFi check
  hosts: proxmox_rpies
  become: yes

  tasks:
    - name: Create the checkwifi.sh script
      copy:
        dest: /usr/local/bin/checkwifi.sh
        content: |
          ping -c4 192.168.1.1 > /dev/null

          if [ $? != 0 ]
          then
            echo "No network connection, restarting network services"
            /bin/systemctl restart networking
        mode: '0755'
        owner: root
        group: root

    - name: Add cron job to execute checkwifi.sh every 5 minutes
      cron:
        name: "Check WiFi connection"
        minute: "*/5"
        user: root
        job: "/usr/bin/sudo -H /usr/local/bin/checkwifi.sh >> /dev/null 2>&1"
